version: "3"
services:
  consul1:
    build: .
    hostname: "consul1"
    container_name: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "consul agent -bootstrap -server -data-dir=/var/lib/consul -ui -client 0.0.0.0" 

  consul2:
    build: .
    hostname: "consul2"
    container_name: "consul2"
    ports:
      - "8400"
      - "8500"
      - "8600"
    command: "consul agent -retry-join=consul1 -data-dir=/var/lib/consul"
    links:
      - "consul1"

  consul3:
    build: .
    hostname: "consul3"
    container_name: "consul3"
    ports:
      - "8400"
      - "8500"
      - "8600"
    command: "consul agent -retry-join=consul1 -data-dir=/var/lib/consul"
    links:
      - "consul1"
